import type {
  AssessmentQuestion,
  CompanyProfile,
  Evidence,
  RemediationTask,
  Risk,
  AnswerValue,
} from "./grc-types";

export const SEED_COMPANY: CompanyProfile = {
  name: "CloudCart Retail",
  industry: "E-commerce / Retail",
  employees: 75,
  dataTypes: "Customer PII, payment card data (PCI), order history, employee HR records",
  complianceGoal: "Achieve SOC 2 Type II readiness and align with NIST CSF 2.0",
  maturity: "Developing",
  systems: "Shopify Plus, AWS, Okta, Google Workspace, Slack, NetSuite, Stripe",
  owner: "Jordan Reyes, Director of IT & Security",
};

export const QUESTIONS: AssessmentQuestion[] = [
  {
    id: "Q-MFA",
    controlArea: "Identity & Access Management",
    question: "Is multi-factor authentication (MFA) enforced for all employees on critical systems?",
    nist: "Protect",
    riskTitle: "MFA not enforced on critical systems",
    riskDescription: "Lack of MFA exposes accounts to credential-based attacks and account takeover.",
    asset: "Okta SSO, AWS Console, Email",
    likelihood: 4,
    impact: 5,
    remediation: "Enforce MFA via Okta for all SaaS apps and AWS root/admin accounts.",
    evidenceName: "MFA enforcement policy screenshot",
  },
  {
    id: "Q-PWD",
    controlArea: "Identity & Access Management",
    question: "Is a formal password policy defined, documented, and technically enforced?",
    nist: "Protect",
    riskTitle: "Weak or undocumented password policy",
    riskDescription: "Weak password requirements increase brute-force and reuse risk across systems.",
    asset: "Okta, Active Directory",
    likelihood: 3,
    impact: 4,
    remediation: "Publish password policy; enforce length, complexity, and breach detection in Okta.",
    evidenceName: "Password policy document",
  },
  {
    id: "Q-ACC",
    controlArea: "Access Management",
    question: "Are user access reviews performed at least quarterly for privileged systems?",
    nist: "Protect",
    riskTitle: "No periodic access reviews",
    riskDescription: "Stale or excessive access leads to privilege creep and insider risk.",
    asset: "All SaaS systems",
    likelihood: 4,
    impact: 4,
    remediation: "Implement quarterly access review process owned by IT with manager attestation.",
    evidenceName: "Quarterly access review report",
  },
  {
    id: "Q-ONB",
    controlArea: "HR Security",
    question: "Are formal onboarding and offboarding procedures used to grant and revoke access?",
    nist: "Protect",
    riskTitle: "Inconsistent onboarding/offboarding",
    riskDescription: "Departed employees may retain access, exposing data and systems.",
    asset: "HRIS, Okta",
    likelihood: 4,
    impact: 4,
    remediation: "Automate joiner/mover/leaver workflow between HRIS and Okta.",
    evidenceName: "Joiner/leaver SOP",
  },
  {
    id: "Q-ENC",
    controlArea: "Data Protection",
    question: "Is sensitive data encrypted at rest and in transit across all production systems?",
    nist: "Protect",
    riskTitle: "Inconsistent data encryption",
    riskDescription: "Unencrypted data exposes PII and payment data in case of breach.",
    asset: "RDS, S3, backups",
    likelihood: 3,
    impact: 5,
    remediation: "Enable KMS encryption on all S3 buckets, RDS, and EBS volumes; enforce TLS 1.2+.",
    evidenceName: "Encryption configuration export",
  },
  {
    id: "Q-BAK",
    controlArea: "Resilience",
    question: "Are backups tested through documented restore exercises at least annually?",
    nist: "Recover",
    riskTitle: "Backups not tested via restore",
    riskDescription: "Untested backups may fail during a real incident, prolonging downtime.",
    asset: "AWS Backup, NetSuite",
    likelihood: 3,
    impact: 5,
    remediation: "Schedule semi-annual restore tests and document results.",
    evidenceName: "Backup restore test results",
  },
  {
    id: "Q-IRP",
    controlArea: "Incident Response",
    question: "Is a documented incident response plan in place and tested annually?",
    nist: "Respond",
    riskTitle: "No tested incident response plan",
    riskDescription: "Without a tested IR plan, response time and containment will suffer.",
    asset: "Enterprise-wide",
    likelihood: 3,
    impact: 5,
    remediation: "Draft IR plan; run a tabletop exercise quarterly.",
    evidenceName: "Incident response plan & tabletop notes",
  },
  {
    id: "Q-SAT",
    controlArea: "Awareness & Training",
    question: "Do all employees complete security awareness training at hire and annually?",
    nist: "Protect",
    riskTitle: "Inconsistent security awareness training",
    riskDescription: "Untrained staff increase phishing and social engineering risk.",
    asset: "Workforce",
    likelihood: 4,
    impact: 3,
    remediation: "Deploy KnowBe4 training with quarterly phishing simulations.",
    evidenceName: "Training completion report",
  },
  {
    id: "Q-VEN",
    controlArea: "Third-Party Risk",
    question: "Are vendors risk-assessed before onboarding and reviewed annually?",
    nist: "Govern",
    riskTitle: "No vendor risk management process",
    riskDescription: "Unvetted vendors may introduce supply chain and data exposure risk.",
    asset: "Vendor ecosystem",
    likelihood: 4,
    impact: 4,
    remediation: "Establish vendor intake questionnaire and annual review cycle.",
    evidenceName: "Vendor assessment form",
  },
  {
    id: "Q-VUL",
    controlArea: "Vulnerability Management",
    question: "Are systems scanned for vulnerabilities monthly with remediation SLAs?",
    nist: "Identify",
    riskTitle: "No formal vulnerability management",
    riskDescription: "Unpatched vulnerabilities can be exploited for initial access.",
    asset: "AWS workloads, endpoints",
    likelihood: 4,
    impact: 4,
    remediation: "Deploy Tenable/Qualys with monthly scans and SLAs by severity.",
    evidenceName: "Vulnerability scan report",
  },
  {
    id: "Q-LOG",
    controlArea: "Logging & Monitoring",
    question: "Are security logs centrally collected and reviewed for anomalies?",
    nist: "Detect",
    riskTitle: "Logs not centrally reviewed",
    riskDescription: "Without log review, malicious activity may go undetected for months.",
    asset: "AWS CloudTrail, Okta logs",
    likelihood: 4,
    impact: 4,
    remediation: "Centralize logs in SIEM (Datadog/Splunk) with detection rules.",
    evidenceName: "SIEM dashboard screenshot",
  },
  {
    id: "Q-POL",
    controlArea: "Governance",
    question: "Are security policies documented, approved, and reviewed annually?",
    nist: "Govern",
    riskTitle: "Incomplete policy documentation",
    riskDescription: "Gaps in policy create audit findings and inconsistent operations.",
    asset: "Policy library",
    likelihood: 3,
    impact: 3,
    remediation: "Adopt SOC 2 policy pack; assign owners; review annually.",
    evidenceName: "Approved policy set",
  },
  {
    id: "Q-ASS",
    controlArea: "Asset Management",
    question: "Is there a complete and up-to-date inventory of hardware and software assets?",
    nist: "Identify",
    riskTitle: "No comprehensive asset inventory",
    riskDescription: "Unknown assets cannot be protected, monitored, or patched.",
    asset: "Endpoints, cloud workloads",
    likelihood: 4,
    impact: 3,
    remediation: "Deploy Kandji + AWS Config aggregator; reconcile monthly.",
    evidenceName: "Asset inventory export",
  },
  {
    id: "Q-EDR",
    controlArea: "Endpoint Security",
    question: "Is endpoint protection (EDR) deployed on every corporate device?",
    nist: "Protect",
    riskTitle: "Incomplete endpoint protection coverage",
    riskDescription: "Unprotected endpoints are a common ransomware entry point.",
    asset: "Laptops, servers",
    likelihood: 3,
    impact: 4,
    remediation: "Deploy CrowdStrike Falcon via MDM; alert on missing coverage.",
    evidenceName: "EDR coverage report",
  },
  {
    id: "Q-BCP",
    controlArea: "Business Continuity",
    question: "Is a business continuity / disaster recovery plan documented and tested?",
    nist: "Recover",
    riskTitle: "No BCP/DR plan in place",
    riskDescription: "An outage could result in extended downtime and revenue loss.",
    asset: "Enterprise-wide",
    likelihood: 3,
    impact: 5,
    remediation: "Document BCP/DR with RTO/RPO; run annual failover test.",
    evidenceName: "BCP/DR plan",
  },
];

export const SEED_ANSWERS: Record<string, AnswerValue> = {
  "Q-MFA": "Partially",
  "Q-PWD": "Yes",
  "Q-ACC": "No",
  "Q-ONB": "Partially",
  "Q-ENC": "Yes",
  "Q-BAK": "No",
  "Q-IRP": "No",
  "Q-SAT": "Partially",
  "Q-VEN": "No",
  "Q-VUL": "Partially",
  "Q-LOG": "Not Sure",
  "Q-POL": "Partially",
  "Q-ASS": "No",
  "Q-EDR": "Yes",
  "Q-BCP": "No",
};

const OWNERS = [
  "Jordan Reyes",
  "Priya Shah",
  "Marcus Lee",
  "Elena Volkov",
  "Sam Okafor",
];

function daysFromNow(d: number): string {
  const date = new Date();
  date.setDate(date.getDate() + d);
  return date.toISOString().slice(0, 10);
}

export function generateRisksFromAnswers(
  answers: Record<string, AnswerValue>,
): Risk[] {
  const risks: Risk[] = [];
  let n = 1;
  for (const q of QUESTIONS) {
    const a = answers[q.id];
    if (a === "Yes" || !a) continue;
    // adjust likelihood by answer strength
    let likelihood = q.likelihood;
    if (a === "Partially") likelihood = Math.max(2, q.likelihood - 1);
    if (a === "Not Sure") likelihood = Math.max(3, q.likelihood);
    const owner = OWNERS[n % OWNERS.length];
    risks.push({
      id: `R-${String(n).padStart(3, "0")}`,
      title: q.riskTitle,
      description: q.riskDescription + (a === "Not Sure" ? " (Control state unverified.)" : ""),
      asset: q.asset,
      likelihood,
      impact: q.impact,
      owner,
      status: "Open",
      nist: q.nist,
      remediation: q.remediation,
      dueDate: daysFromNow(30 + n * 7),
      sourceQuestionId: q.id,
    });
    n++;
  }
  return risks;
}

export function generateTasksFromRisks(risks: Risk[]): RemediationTask[] {
  return risks.map((r, i) => {
    const score = r.likelihood * r.impact;
    const priority =
      score >= 16 ? "Critical" : score >= 9 ? "High" : score >= 4 ? "Medium" : "Low";
    const statuses = ["Not Started", "In Progress", "Blocked", "Completed"] as const;
    return {
      id: `T-${String(i + 1).padStart(3, "0")}`,
      riskId: r.id,
      action: r.remediation,
      priority,
      owner: r.owner,
      dueDate: r.dueDate,
      status: statuses[i % 4],
      evidenceNeeded:
        QUESTIONS.find((q) => q.id === r.sourceQuestionId)?.evidenceName ?? "Control evidence",
      notes: "",
    };
  });
}

export const SEED_EVIDENCE: Evidence[] = [
  {
    id: "E-001",
    controlArea: "Identity & Access Management",
    name: "MFA policy screenshot",
    description: "Screenshot of Okta MFA enforcement policy applied to all users.",
    owner: "Priya Shah",
    status: "Collected",
    collectionDate: daysFromNow(-10),
    notes: "Pending review by audit lead.",
    nist: "Protect",
  },
  {
    id: "E-002",
    controlArea: "Access Management",
    name: "Quarterly access review report",
    description: "Q1 access review attestations for privileged systems.",
    owner: "Marcus Lee",
    status: "Missing",
    collectionDate: "",
    notes: "Process not yet implemented.",
    nist: "Protect",
  },
  {
    id: "E-003",
    controlArea: "Awareness & Training",
    name: "Security awareness training completion report",
    description: "KnowBe4 completion export for the prior quarter.",
    owner: "Sam Okafor",
    status: "Requested",
    collectionDate: "",
    notes: "Vendor onboarding in progress.",
    nist: "Protect",
  },
  {
    id: "E-004",
    controlArea: "Resilience",
    name: "Backup restore test results",
    description: "Documented results from the latest restore exercise.",
    owner: "Jordan Reyes",
    status: "Missing",
    collectionDate: "",
    notes: "No tests performed in last 12 months.",
    nist: "Recover",
  },
  {
    id: "E-005",
    controlArea: "Incident Response",
    name: "Incident response plan",
    description: "Approved IR plan with roles, severities, and escalation paths.",
    owner: "Jordan Reyes",
    status: "Missing",
    collectionDate: "",
    notes: "Draft in progress.",
    nist: "Respond",
  },
  {
    id: "E-006",
    controlArea: "Third-Party Risk",
    name: "Vendor assessment form",
    description: "Vendor security assessment for top 10 critical vendors.",
    owner: "Elena Volkov",
    status: "Requested",
    collectionDate: "",
    notes: "Awaiting responses from 4 vendors.",
    nist: "Govern",
  },
  {
    id: "E-007",
    controlArea: "Asset Management",
    name: "Asset inventory export",
    description: "Consolidated hardware and software inventory.",
    owner: "Marcus Lee",
    status: "Collected",
    collectionDate: daysFromNow(-3),
    notes: "Reconciliation underway.",
    nist: "Identify",
  },
  {
    id: "E-008",
    controlArea: "Logging & Monitoring",
    name: "SIEM detection coverage",
    description: "Detection rule inventory and recent alert triage notes.",
    owner: "Priya Shah",
    status: "Missing",
    collectionDate: "",
    notes: "SIEM not yet centralized.",
    nist: "Detect",
  },
  {
    id: "E-009",
    controlArea: "Governance",
    name: "Approved security policy set",
    description: "Board-approved information security policies.",
    owner: "Jordan Reyes",
    status: "Reviewed",
    collectionDate: daysFromNow(-30),
    notes: "Final approval pending.",
    nist: "Govern",
  },
];