/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RemediationRouteImport } from './routes/remediation'
import { Route as NistRouteImport } from './routes/nist'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'

const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RemediationRoute = RemediationRouteImport.update({
  id: '/remediation',
  path: '/remediation',
  getParentRoute: () => rootRouteImport,
} as any)
const NistRoute = NistRouteImport.update({
  id: '/nist',
  path: '/nist',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/company': typeof CompanyRoute
  '/evidence': typeof EvidenceRoute
  '/nist': typeof NistRoute
  '/remediation': typeof RemediationRoute
  '/report': typeof ReportRoute
  '/risks': typeof RisksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/company': typeof CompanyRoute
  '/evidence': typeof EvidenceRoute
  '/nist': typeof NistRoute
  '/remediation': typeof RemediationRoute
  '/report': typeof ReportRoute
  '/risks': typeof RisksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/company': typeof CompanyRoute
  '/evidence': typeof EvidenceRoute
  '/nist': typeof NistRoute
  '/remediation': typeof RemediationRoute
  '/report': typeof ReportRoute
  '/risks': typeof RisksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/company'
    | '/evidence'
    | '/nist'
    | '/remediation'
    | '/report'
    | '/risks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/company'
    | '/evidence'
    | '/nist'
    | '/remediation'
    | '/report'
    | '/risks'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/company'
    | '/evidence'
    | '/nist'
    | '/remediation'
    | '/report'
    | '/risks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  CompanyRoute: typeof CompanyRoute
  EvidenceRoute: typeof EvidenceRoute
  NistRoute: typeof NistRoute
  RemediationRoute: typeof RemediationRoute
  ReportRoute: typeof ReportRoute
  RisksRoute: typeof RisksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remediation': {
      id: '/remediation'
      path: '/remediation'
      fullPath: '/remediation'
      preLoaderRoute: typeof RemediationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nist': {
      id: '/nist'
      path: '/nist'
      fullPath: '/nist'
      preLoaderRoute: typeof NistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  CompanyRoute: CompanyRoute,
  EvidenceRoute: EvidenceRoute,
  NistRoute: NistRoute,
  RemediationRoute: RemediationRoute,
  ReportRoute: ReportRoute,
  RisksRoute: RisksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
